### ISSUE TITLE
Cannot move (mouse on mac)

### ISSUE THREAD

**Issue by TwoHorus** [cristicbz/rust-doom#122]
Console:
executed in GitHub/rust-doom

target/release/rs_doom --iwad Doom1.WAD
ERROR:wad::visitor: Unknown linedef special type: 48  <- this line multiple times.

**Comment by cristicbz** [comment]
This is weird, could you try now? I've pushed a PR to bring my dependencies up to day, I think glutin's behaviour on mac improved since the last time I'd updated.

**Comment by cristicbz** [comment]
(re-open if the issue persists)

**Comment by JamesDunne** [comment]
This issue still persists. I was able to reproduce first try after building it on MacOS 10.12.6 with rustc 1.35.0 (3c235d560 2019-05-20)`.

The mouse is stuck to the middle of the screen and frozen in place. Any time I try to move it snaps back to the center. The view angle depends on if I have one or two monitors connected. Trying with one monitor alone still fails. I use two external monitors usually and I have the MacBook physically closed so its built-in primary display is not being used.

**Comment by cristicbz** [comment]
Argh, that sucks. I don't have a mac right now, but I'll try as soon as I get my hands on one, sorry :(
